add testing; bot breaks pytest exit...

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -8,3 +8,12 @@ else
     printf "commit-msg hook failed (add --no-verify to bypass)\n"
     exit 1
 fi
+
+make test
+if [[ $? == 0 ]]; then
+    printf "good Commit"
+else
+    printf "Test Issues! Please resolve before commiting.\n"
+    printf "commit-msg hook failed (add --no-verify to bypass)\n"
+    exit 1
+fi
